/*
 * Copyright 2026 NWChemEx-Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
#include <array>
#include <simde/simde.hpp>
#include <tensorwrapper/buffer/contiguous.hpp>
#include <tensorwrapper/shape/smooth.hpp>
#include <tensorwrapper/utilities/make_tensor.hpp>
#include <vector>

namespace test_eigen_solver {

// H2 dimer (4 H, STO-3G) Fock and overlap from the core-guess
// diagonalization step. Generated by the SCFDriver integration test dump.

inline constexpr std::array<double, 16> h2_dimer_fock_data{
  -1.5208138831078950e+00, -1.2688563238876407e+00, -1.4288125943995872e-01,
  -3.5691640230145288e-02, -1.2688563238876407e+00, -1.6807172836050259e+00,
  -4.4451594013857459e-01, -1.4288125943995875e-01, -1.4288125943995875e-01,
  -4.4451594013857459e-01, -1.6807172836050259e+00, -1.2688563238876405e+00,
  -3.5691640230145288e-02, -1.4288125943995872e-01, -1.2688563238876402e+00,
  -1.5208138831078946e+00};

inline constexpr std::array<double, 16> h2_dimer_overlap_data{
  1.0000000000000000e+00, 6.5987566030170408e-01, 6.7949947315035300e-02,
  1.5819246523949011e-02, 6.5987566030170408e-01, 1.0000000000000000e+00,
  2.2618964447525747e-01, 6.7949947315035300e-02, 6.7949947315035300e-02,
  2.2618964447525747e-01, 1.0000000000000000e+00, 6.5987566030170408e-01,
  1.5819246523949011e-02, 6.7949947315035300e-02, 6.5987566030170408e-01,
  1.0000000000000000e+00};

// Input Fock matrix
template<typename FloatType>
inline simde::type::tensor h2_dimer_fock_as() {
    using tensorwrapper::utilities::make_tensor;
    std::vector<FloatType> elements(h2_dimer_fock_data.begin(),
                                    h2_dimer_fock_data.end());
    for(auto& x : elements) { x = static_cast<FloatType>(x); }
    return make_tensor({4, 4}, std::move(elements));
}

// Input overlap matrix
template<typename FloatType>
inline simde::type::tensor h2_dimer_overlap_as() {
    using tensorwrapper::utilities::make_tensor;
    std::vector<FloatType> elements(h2_dimer_overlap_data.begin(),
                                    h2_dimer_overlap_data.end());
    for(auto& x : elements) { x = static_cast<FloatType>(x); }
    return make_tensor({4, 4}, std::move(elements));
}

// Correct eigenvalues
template<typename FloatType>
inline simde::type::tensor h2_dimer_evals() {
    using tensorwrapper::utilities::make_tensor;
    std::vector corr_data{static_cast<FloatType>(-1.7782489061355591),
                          static_cast<FloatType>(-1.6984246969223022),
                          static_cast<FloatType>(-1.0329644680023193),
                          static_cast<FloatType>(-0.8134391903877258)};
    return make_tensor({4}, corr_data);
}

} // namespace test_eigen_solver
